---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# DFapplyFunction Package

<!-- badges: start -->
<!-- badges: end -->

Create an R package with df_apply() function in it. 

## Installation

Follow the blow instruction to install the Function_Pkg package:

``` r
devtools::install_github('haoping-he/Function_Pkg')
```



## Example

This is an example to show you how to apply the function df_apply() to your desired dataframe in order to convert it into a different format.

```{r example, message=FALSE}
library(FunctionPkg)
 n <- 5L
 TestData <- dplyr::tibble( 
                 double = c(5.002, 3.221, 4.008, 5.112, 4.779),
                 integer = c(0, 10, 20, 30, 40),
                cap = LETTERS[1L:n],
                 low = letters[1L:n])

TestData  
 
df_apply(TestData, round, is.numeric, digits = 1)


TestData |>  df_apply(toupper, is_character)
TestData |> df_apply(round, is.numeric, toupper, digits = 2)
TestData |> df_apply(round, is.numeric, as.factor, digits = -1)
```


