---
title: "HaopingHe-index"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HaopingHe-index}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



<!-- ```{r, echo=FALSE} -->

<!-- #Average fruit consumption per person, measured in kilograms per year. -->
<!-- fruit <- read.csv("/home/yh38/DATA303/Data303-Project/303Visualization/docs/plotly-projects/Haoping-He/fruit-consumption-per-capita.csv") -->

<!-- #Average fruit consumption per person, differentiated by fruit types, measured in kilograms per year. -->
<!-- fruittype <-  read.csv("/home/yh38/DATA303/Data303-Project/303Visualization/docs/plotly-projects/Haoping-He/fruit-consumption-by-fruit-type.csv") -->


<!-- Fruit<- fruit %>% dplyr::filter(Year == 2013) %>% dplyr::select(-Year) -->
<!-- Fruit_Type<- fruittype%>%dplyr::filter(Year == 2013) %>% dplyr::select(-Year, -Code) %>% -->
<!--   dplyr::rename(Bananas = Food.Supply...Crops.Primary.Equivalent...Bananas...2615...Food.supply.quantity..kg.capita.yr....645...kg,  -->
<!--          Dates = Food.Supply...Crops.Primary.Equivalent...Dates...2619...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Citrus = Food.Supply...Crops.Primary.Equivalent...Citrus..Other...2614...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Oranges = Food.Supply...Crops.Primary.Equivalent...Oranges..Mandarines...2611...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Apples = Food.Supply...Crops.Primary.Equivalent...Apples.and.products...2617...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Lemons = Food.Supply...Crops.Primary.Equivalent...Lemons..Limes.and.products...2612...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Grapes = Food.Supply...Crops.Primary.Equivalent...Grapes.and.products..excl.wine....2620...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Grapefruit = Food.Supply...Crops.Primary.Equivalent...Grapefruit.and.products...2613...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Pineapples = Food.Supply...Crops.Primary.Equivalent...Pineapples.and.products...2618...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Plantains = Food.Supply...Crops.Primary.Equivalent...Plantains...2616...Food.supply.quantity..kg.capita.yr....645...kg, -->
<!--          Other = Food.Supply...Crops.Primary.Equivalent...Fruits..Other...2625...Food.supply.quantity..kg.capita.yr....645...kg) -->

<!-- Data <- Fruit %>% dplyr::left_join(Fruit_Type, by = 'Entity') %>% -->
<!--   dplyr::rename(Country = Entity,  -->
<!--          Fruit = Fruits...Excluding.Wine...Food.supply.quantity..kg.capita.yr...FAO..2020.) -->

<!-- Data[is.na(Data)] = 0 -->


<!-- ``` -->


```{r get-excel, message=FALSE}
library(dplyr)
library(FunctionPkg)
Pivot_Data_Country <- FunctionPkg::Pivot_Data_Country
Data <- FunctionPkg::FruitData
```


```{r echo=FALSE, warning=FALSE}
Top_10_Countries <- Data %>% 
  dplyr::arrange(desc(Fruit))%>%
  utils::head(15)

Pivot_Data <- Data%>%
  dplyr::select("Country", 'Code', "Bananas" , "Oranges", "Apples" , "Grapes", "Plantains")%>%
  tidyr::pivot_longer(
    cols = c("Bananas" , "Oranges", "Apples" , "Grapes", "Plantains"),
    names_to = 'FruitType',
    values_to = 'Consumption'
  ) 

Countries <- Data %>% dplyr::arrange(desc(Fruit)) %>% utils::head(10)%>% dplyr::select(Country)


Pivot_Data_Country <-Pivot_Data %>% 
  dplyr::left_join(Data %>% dplyr::select(Country, Fruit), on = Country) %>% 
  dplyr::filter(Country %in% Countries$Country)%>% dplyr::arrange(desc(Fruit))
```
\
\


# Top 10 countries that consumed most fruits per capita
```{r, echo=FALSE, warning=FALSE}

Top_10_Countries <- Data %>% 
  dplyr::arrange(desc(Fruit))%>%
  utils::head(15)
```


\
\
\

# Fruit consumption by fruit type (2013)

```{r, echo=FALSE, warning=FALSE}

Data$hover <- with(Data, paste( '<b>' , Country , '</b>' , '<br>', 
                                           "Bananas", '<b>' , Bananas,'</b>', "kg/year", "<br>", 
                                           "Dates", '<b>' , Dates,'</b>', "kg/year", "<br>",
                                            "Citrus", '<b>' , Citrus,'</b>', "kg/year", "<br>",
                                            "Oranges", '<b>' , Oranges,'</b>', "kg/year", "<br>",
                                           "Apples", '<b>' , Apples,'</b>', "kg/year", "<br>",
                                        "Lemons", '<b>' , Lemons,'</b>', "kg/year", "<br>",
                                        "Grapes", '<b>' , Grapes,'</b>', "kg/year", "<br>",
                                        "Grapefruit", '<b>' , Grapefruit,'</b>', "kg/year", "<br>",
                                "Pineapples", '<b>' , Pineapples,'</b>', "kg/year", "<br>",
                                "Plantains", '<b>' , Plantains,'</b>', "kg/year", "<br>",
                                "Other", '<b>' , Other,'</b>', "kg/year", "<br>"))
    
```

```{r, echo=FALSE, warning=FALSE}
  

D1 <- Data%>%
  dplyr::select(-c("Code", "hover"))%>%
  tidyr::pivot_longer(
    cols = (-Country),
    names_to = 'FruitType',
    values_to = 'value'
  )

D2 <- D1 %>% 
  dplyr::left_join(Data %>% dplyr::select(Country, Code, Fruit), on = Country)


countryKey <- plotly::highlight_key(Data, ~Country)

base <- plotly::plot_ly(countryKey, color = I("black")) %>% 
  dplyr::group_by(Country)

plot11 <- D2 %>%
      plotly::highlight_key(~Country) %>%
     plotly::plot_ly(type='choropleth', 
                      locations=D2$Code, 
                      z=D2$Fruit,  
                      #text=Data$hover, 
                      colorscale="Viridis") %>% 
  plotly::layout(title = 'Fruit Consumption')  %>% 
    plotly::highlight("plotly_click", persistent = FALSE, dynamic = TRUE)

plot22 <- D2 %>% 
    plotly::plot_ly(x = ~Fruit, y = ~value)  %>%
    plotly::add_bars() %>%
  #layout(barmode = "overlay") %>%
  plotly::highlight("plotly_click")

```


# Check Fruit Consumption in Each Country
```{r, echo=FALSE, warning=FALSE}


countryKey <- plotly::highlight_key(Pivot_Data_Country, ~Country)


line <- countryKey  %>% 
  plotly::plot_ly( x = ~ reorder(Country, -Fruit), y = ~Fruit, 
name = 'Fruit total', type = 'scatter', mode = 'lines+markers',
  text = paste("<br>Country: ", Pivot_Data_Country$Country,"<br>",
                 Pivot_Data_Country$Fruit, 'kg/year'),
  hoverinfo = 'text') %>% 
  plotly::layout(title= "Which Country Eats the Most Fruits Per Capita?")%>% 
  plotly::highlight("plotly_click")


bar <- countryKey %>% 
  plotly::plot_ly()  %>%
  plotly::add_bars(x = ~FruitType, y = ~Consumption, color = 'green') %>% 
  plotly::layout(barmode = "overlay")

crosstalk::bscols(line,bar) 

```


```{r, echo=FALSE, warning=FALSE}
# library(crosstalk)
# countryKey <- highlight_key(Pivot_Data, ~Country)
# 
# map <- countryKey %>%
#   plot_ly()%>%
#   group_by(Country, Code) %>%
#   summarise(Consumption = sum(Consumption, na.rm = TRUE)) %>%
#   add_choropleth(
#     locations=~Code, 
#     z=~Consumption,  
#     #text=Data$hover, 
#     colorscale="Viridis") %>% 
#   layout(title = 'Fruit Consumption')  %>% 
#   highlight("plotly_click", persistent = FALSE, dynamic = TRUE)
# 
# barplot <- countryKey %>% 
#   plot_ly(x = ~FruitType, y = ~Consumption)  %>%
#   add_bars() 
#   #layout(barmode = "overlay")
# 
# dotplot <- countryKey %>%
#   plot_ly()%>%
#   group_by(Country, Code) %>%
#   summarise(Consumption = sum(Consumption, na.rm = TRUE)) %>%
#   add_markers(
#     x = ~Country, y = ~Consumption
#   )%>%
#  highlight("plotly_click")
# 
# crosstalk::bscols(dotplot,barplot) 


```





```{r echo=FALSE}
   
       

fig3 <-  plotly::plot_ly(Data, type='choropleth', 
                      locations=Data$Code, 
                      z=Data$Fruit,  
                      text=Data$hover, 
                      colorscale="Viridis") %>% 
  plotly::layout(title = 'Fruit Consumption by fruit type/country(2013)')

fig3
```
